---
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    command: >
      /usr/local/bin/etcd
      --name etcd0
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd:2379
      --initial-cluster-state new
    ports:
      - "2379:2379"
    restart: unless-stopped

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600"
      - "3000:3000"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

  0api:
    image: wilful/nullae:${NULLAE_VERSION:-latest}
    build:
      context: .
      target: final
    restart: always
    scale: 1
    command: /bin/0api
    environment:
      NULLAE_DOMAIN: local
      RUST_LOG: debug
      NULLAE_CONSUL_URL: http://caddy:8500

  consul1:
    image: consul:1.15.4
    command: >
      agent -server -bootstrap-expect=3 -node=consul1 -client=0.0.0.0
      -ui -retry-join=consul2 -retry-join=consul3
    volumes:
      - db-data1:/consul/data
    restart: unless-stopped

  consul2:
    image: consul:1.15.4
    command: >
      agent -server -bootstrap-expect=3 -node=consul2 -client=0.0.0.0
      -ui -retry-join=consul1 -retry-join=consul3
    volumes:
      - db-data2:/consul/data
    restart: unless-stopped

  consul3:
    image: consul:1.15.4
    command: >
      agent -server -bootstrap-expect=3 -node=consul3 -client=0.0.0.0
      -ui -retry-join=consul1 -retry-join=consul2
    volumes:
      - db-data3:/consul/data
    restart: unless-stopped

volumes:
  db-data1: {}
  db-data2: {}
  db-data3: {}
