[package]
name = "nullae-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
reqwest.workspace = true
uuid = { version = "1.18.1", features = ["v4", "serde"] }
serde_json.workspace = true
serde.workspace = true
chrono = { version = "0.4.42", default-features = false, features = [
  "serde",
  "clock",
] }
hostname = "0.4.1"
pnet = "0.35.0"
sha2 = "0.10.9"
hex = "0.4.3"
tabled = "0.20.0"
base64 = "0.22.1"
once_cell = "1.21.3"
nullae-macros.workspace = true
futures = "0.3.31"
url.workspace = true
dotenvy.workspace = true
