[package]
name = "nullae-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
gloo = "0.11.0"
js-sys = "0.3.81"
reqwest.workspace = true
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.104"
wasm-bindgen-futures = "0.4.54"
yew = { version = "0.21.0", features = ["csr"] }
serde_json.workspace = true
serde.workspace = true
tracing.workspace = true
url.workspace = true

[dependencies.web-sys]
version = "0.3.81"
features = ["HtmlInputElement", "HtmlSelectElement", "Window", "Navigator", "Clipboard"]
